DESCRIBE CALIBER2_ASSESSMENT;

SELECT COUNT(*) FROM CALIBER2_category;

DESCRIBE CALIBER2_GRADE;

SELECT * FROM CALIBER2_ASSESSMENT;

SELECT * FROM CALIBER2_PANEL_FEEDBACK
JOIN CALIBER2_PANEL ON CALIBER2_PANEL_FEEDBACK.PANEL_ID = CALIBER2_PANEL.PANEL_ID;

--ASSESSMENT TABLE ALTERATIONS
ALTER TABLE "CALIBER2_ASSESSMENT" ADD PRIMARY KEY ("ASSESSMENT_ID");

ALTER TABLE "CALIBER2_ASSESSMENT" ADD FOREIGN KEY ("BATCH_ID") REFERENCES CALIBER2_BATCH ("BATCH_ID") ENABLE;

ALTER TABLE "CALIBER2_ASSESSMENT" ADD FOREIGN KEY ("ASSESSMENT_CATEGORY") REFERENCES CALIBER2_CATEGORY ("CATEGORY_ID") ENABLE;

ALTER TABLE "CALIBER2_ASSESSMENT" ADD FOREIGN KEY ("RAW_SCORE") REFERENCES CALIBER2_GRADE ("SCORE") ENABLE;
-------------------------------------

--ASSIGNMENT TABLE ALTERATIONS
ALTER TABLE "CALIBER2_ASSIGNMENT" ADD PRIMARY KEY ("ASSINGMENT_ID");

ALTER TABLE "CALIBER2_ASSIGNMENT" ADD FOREIGN KEY ("TRAINEE_ID") REFERENCES CALIBER2_TRAINEE ("TRAINEE_ID") ENABLE;

ALTER TABLE "CALIBER2_ASSIGNMENT" ADD FOREIGN KEY ("BATCH_ID") REFERENCES CALIBER2_BATCH ("BATCH_ID") ENABLE;

ALTER TABLE "CALIBER2_ASSIGNMENT" ADD FOREIGN KEY ("TRAINEE_ID") REFERENCES CALIBER2_TRAINEE ("TRAINEE_ID") ENABLE;
--------------------------------------

--PANEL FEEDBACK TABLE ALTERATIONS
ALTER TABLE "CALIBER2_PANEL_FEEDBACK" ADD PRIMARY KEY ("PANEL_FEEDBACK_ID");
--------------------------------------

--TRAINEE NOTE TABLE ALTERATIONS
ALTER TABLE "CALIBER2_TRAINEE_NOTE" ADD FOREIGN KEY ("ASSIGNMENT_ID") REFERENCES CALIBER2_ASSIGNMENT ("ASSINGMENT_ID") ENABLE;
--------------------------------------

--GRADE TABLE ALTERATIONS
ALTER TABLE "CALIBER2_GRADE" ADD FOREIGN KEY ("ASSIGNMENT_ID") REFERENCES CALIBER2_ASSIGNMENT ("ASSINGMENT_ID") ENABLE;
--------------------------------------

--BATCH TABLE ALTERATIONS
ALTER TABLE "CALIBER2_BATCH" ADD PRIMARY KEY ("BATCH_ID");
-------------------------------------

SELECT * FROM CALIBER.CALIBER_NOTE;

COMMIT;