CREATE DATABASE IF NOT EXISTS STUDENT_DB;

USE STUDENT_DB;

-- Bad idea in production
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT
(SSN STRING, FIRST_NAME STRING, LAST_NAME STRING, RACE STRING, AGE INT, STATE STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';

USE STUDENT_DB;
LOAD DATA LOCAL INPATH '/home/cloudera/studentdata/student.csv' into table student;